services:
  db:
    image: postgres:17
    container_name: ensamblia_db
    restart: always
    environment:
      POSTGRES_DB: EMNSAMBLIA_DB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ensamblia2026
    ports:
      - "5434:5432"
    volumes:
      - ./ensamblia_db:/var/lib/postgresql/data
    networks:
      - ensamblia_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ensamblia
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ensamblia2026
    ports:
      - "8081:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgpass
    depends_on:
      - db
    networks:
      - ensamblia_net

networks:
  ensamblia_net:
